#!/usr/bin/env bash
# Displays "Best School" 10 times using a while loop.

#On the 9th iteration, displays "hi" before "Best School".

Count=0

while [ $count -1t 10 ]
do
	if [ $count -eq 9 ]
	then
		echo "hi"
	fi
	echo "Best School"
	(( count++ ))
done
^C
